/*
 * Copyright (c) 2023 -      bosonnetwork.io
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.bosonnetwork.photonmessaging;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jspecify.annotations.Nullable;

import io.bosonnetwork.Id;

/**
 * Represents a message in the Photon messaging.
 */
public interface Message {
	/**
	 * Defines the types of messages supported by the service.
	 */
	enum Type {
		/** Handshake message */
		HANDSHAKE_MESSAGE(0),
		/** Standard user-to-user content. */
		CONTENT_MESSAGE(1),
		/** Internal RPC call or control instructions. */
		CONTROL_MESSAGE(2),
		/** User/Device status updates. */
		STATE_MESSAGE(3);

		private final int value;

		Type(int value) {
			this.value = value;
		}

		/**
		 * Returns the stable numeric value associated with this message type. This value is
		 * used for serialization purposes and is independent of the constant's declaration
		 * order, so it can be safely mapped back via {@link #valueOf(int)}.
		 *
		 * @return the message type value.
		 */
		@JsonValue
		public int value() {
			return value;
		}

		/**
		 * Returns the {@code Type} corresponding to the specified numeric value.
		 *
		 * @param value the numeric value.
		 * @return the corresponding {@code Type}.
		 * @throws IllegalArgumentException if the value is invalid.
		 */
		@JsonCreator
		public static Type valueOf(int value) {
			return switch (value) {
				case 0 -> HANDSHAKE_MESSAGE;
				case 1 -> CONTENT_MESSAGE;
				case 2 -> CONTROL_MESSAGE;
				case 3 -> STATE_MESSAGE;
				default -> throw new IllegalArgumentException("Invalid message type: " + value);
			};
		}
	}

	/**
	 * Returns the unique identifier for this message.
	 * <p>
	 * This ID is generated by the sender's device at the time of creation.
	 * It is guaranteed to be unique across all devices associated with the user
	 * and throughout the message's lifecycle within the network.
	 *
	 * @return the unique message {@link Id}
	 */
	Id getId();

	/**
	 * Returns the store-assigned numeric identifier (rid) of this message.
	 * <p>
	 * Unlike {@link #getId()}, which is the sender-generated content id, the rid is the local
	 * store's auto-incrementing sequence key and is the identifier accepted by
	 * {@link MessagingClient#removeMessage(long)}. It is a device-local detail: the same message
	 * may carry different rids on different devices, and a message that has not yet been persisted
	 * (e.g. an outgoing message before it is stored) reports {@code 0}.
	 *
	 * @return the store-assigned rid, or {@code 0} if this message is not backed by a stored row
	 */
	long getRid();

	/**
	 * Retrieves the identifier of the conversation this message belongs to.
	 *
	 * @return an {@link Optional} holding the conversation ID, or an empty {@code Optional} if
	 *         the message is not yet associated with a conversation (e.g. an outgoing message
	 *         before it is dispatched).
	 */
	Optional<Id> getConversationId();

	/**
	 * Retrieves the identifier of the message recipient.
	 *
	 * @return the recipient's Id
	 */
	Id getRecipient();

	/**
	 * Retrieves the type of this message.
	 *
	 * @return the message Type
	 */
	Type getType();

	/**
	 * Retrieves the identifier of the sender.
	 *
	 * @return an {@link Optional} holding the sender's Id, or an empty {@code Optional} if the
	 *         sender is not set (e.g. a locally-originated message before it is stamped with a
	 *         sender).
	 */
	Optional<Id> getFrom();

	/**
	 * Retrieves the timestamp when the sender created the message.
	 *
	 * @return the creation timestamp in milliseconds
	 */
	long getCreatedAt();

	/**
	 * Retrieves the timestamp indicating when the message was received.
	 * The timestamp is represented in milliseconds since the epoch.
	 *
	 * @return the received timestamp in milliseconds
	 */
	long getReceivedAt();

	/**
	 * Retrieves the timestamp when the message was sent.
	 * The timestamp is represented in milliseconds since the epoch.
	 *
	 * @return the sent timestamp in milliseconds
	 */
	long getSentAt();

	/**
	 * Retrieves the binary payload of this message.
	 * The payload contains the raw data associated with the message,
	 * which may represent text, media, or other types of content depending on the context.
	 *
	 * @return the payload as a byte array
	 */
	byte[] getPayloadAsBytes();

	/**
	 * Retrieves the payload wrapped in a {@link Content} object.
	 *
	 * @return the content representation of the payload
	 */
	Content getPayloadAsContent();

	/**
	 * Represents the content of a message, providing access to its metadata and body.
	 */
	interface Content {
		/**
		 * Retrieves the metadata headers associated with the content.
		 *
		 * @return a map where the keys are header names and the values are the corresponding header values.
		 */
		Map<String, Object> getHeaders();

		/**
		 * Retrieves the content type of the message.
		 * The default content type is "text/plain" if not specified.
		 *
		 * @return the content type as a string, representing the media type (e.g., "text/plain", "application/json").
		 */
		default String getContentType() {
			return getHeaders().getOrDefault(ContentType.HEADER_NAME, ContentType.TEXT).toString();
		}

		/**
		 * Retrieves the content disposition of the message.
		 *
		 * @return an {@link Optional} holding the content disposition, indicating how the
		 *         content is expected to be displayed (e.g., "inline" or "attachment"), or an
		 *         empty {@code Optional} if no disposition header is present.
		 */
		default Optional<ContentDisposition> getContentDisposition() {
			Object disposition = getHeaders().get(ContentDisposition.HEADER_NAME);
			return disposition == null ? Optional.empty() :
					Optional.of(ContentDisposition.parse(disposition.toString()));
		}

		/**
		 * Retrieves the body of the content.
		 *
		 * @param <T> the expected type of the body
		 * @return the body of the content, cast to the specified type
		 */
		<T> T getBody();

		/**
		 * Retrieves the body of the content as a string representation: a text body as it is, a
		 * binary body decoded as UTF-8, and an object body rendered as JSON.
		 *
		 * @return the body of the content as a string; never {@code null}
		 */
		String asText();

		/**
		 * Retrieves the body of the content as an array of bytes: a text body encoded as UTF-8, a
		 * binary body as a defensive copy, and an object body CBOR-encoded.
		 *
		 * @return a byte array representing the body of the content; never {@code null}
		 */
		byte[] asBinary();

		/**
		 * Retrieves the body of the content.
		 *
		 * @param <T> the expected type of the body
		 * @param type the class of the body's type
		 * @return the body of the content, cast to the specified type
		 */
		<T> T asObject(Class<T> type);

		/**
		 * Retrieves the body of the content as a list of elements of the specified type.
		 *
		 * @param <E> the type of elements in the resulting list
		 * @param elementType the class of the elements to cast the body elements to
		 * @return a list of elements of the specified type representing the content body
		 */
		<E> List<E> asList(Class<E> elementType);

		/**
		 * Converts the body of the content into a map with the specified key and value types.
		 *
		 * @param <K> the type of the map keys
		 * @param <V> the type of the map values
		 * @param keyType the class of the keys in the map
		 * @param valueType the class of the values in the map
		 * @return a map containing the body of the content with the specified key and value types,
		 *         or null if the body cannot be converted to the requested map type
		 */
		<K, V> Map<K, V> asMap(Class<K> keyType, Class<V> valueType);
	}

	/**
	 * Message builder is an easy-to-use fluent helper interface to compose and send a message.
	 */
	interface Builder {
		/**
		 * Sets the recipient of the message.
		 *
		 * @param to the recipient's identifier
		 * @return this builder instance
		 */
		Builder to(Id to);

		/**
		 * Adds or removes a metadata header.
		 *
		 * @param name  the name of the header
		 * @param value the value of the header; a {@code null} value will remove the header
		 * @return this builder instance
		 */
		Builder header(String name, @Nullable Object value);

		/**
		 * Sets the content type of the message body.
		 *
		 * @param contentType the media type (e.g., "text/plain", "application/json")
		 * @return this builder instance
		 */
		Builder contentType(String contentType);

		/**
		 * Sets the content disposition of the message body.
		 *
		 * @param contentDisposition the disposition (e.g., "inline" or "attachment")
		 * @return this builder instance
		 */
		Builder contentDisposition(String contentDisposition);

		/**
		 * Sets the content disposition of the message body.
		 *
		 * @param contentDisposition the {@code ContentDisposition} instance specifying
		 *                           the disposition type (e.g., inline or attachment) and optional filename
		 * @return this builder instance
		 */
		Builder contentDisposition(ContentDisposition contentDisposition);

		/**
		 * Sets the message content as a string.
		 * The content is treated as {@code text/plain}. The corresponding
		 * {@code Content-Type} header is assumed as the default and therefore
		 * is not explicitly set.
		 *
		 * @param body the string content
		 * @return this builder instance
		 */
		Builder contentText(String body);

		/**
		 * Sets the message content as a byte array.
		 * The content-type header will be set to "application/octet-stream" if not already set.
		 *
		 * @param body the raw bytes of the content
		 * @return this builder instance
		 */
		Builder contentBinary(byte[] body);

		/**
		 * Sets the message content as an object.
		 * The content-type header will be set to "application/cbor" if not already set.
		 *
		 * @param body the object to be used as the message body
		 * @return this builder instance
		 */
		Builder contentObject(Object body);

		/**
		 * Composes and sends the message.
		 *
		 * @return a {@link CompletableFuture} that will be completed with the sent {@link Message}
		 */
		CompletableFuture<Message> send();
	}
}